[project]
authors = []
license = { text = "MIT" }
requires-python = "<4.0,>=3.9"
dependencies = []
name = "agentevals-monorepo"
version = "0.0.1"
readme = "README.md"

[tool.uv.sources]
evaluators = { path = "./python/evaluators", editable = true }
